
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(425, 300)
        Form.setMinimumSize(QtCore.QSize(250, 300))
        Form.setMaximumSize(QtCore.QSize(519, 300))
        Form.setStyleSheet("QPushButton {background: orange}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_multiply = QtWidgets.QPushButton(self.widget)
        self.pushButton_multiply.setAutoFillBackground(False)
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.gridLayout.addWidget(self.pushButton_multiply, 0, 3, 1, 1)
        self.pushButton_percent = QtWidgets.QPushButton(self.widget)
        self.pushButton_percent.setAutoFillBackground(False)
        self.pushButton_percent.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.gridLayout.addWidget(self.pushButton_percent, 0, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.widget)
        self.pushButton_minus.setAutoFillBackground(False)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.gridLayout.addWidget(self.pushButton_minus, 1, 3, 1, 1)
        self.pushButton_exponent = QtWidgets.QPushButton(self.widget)
        self.pushButton_exponent.setAutoFillBackground(False)
        self.pushButton_exponent.setObjectName("pushButton_exponent")
        self.gridLayout.addWidget(self.pushButton_exponent, 1, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.widget)
        self.pushButton_add.setAutoFillBackground(False)
        self.pushButton_add.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 2, 3, 1, 1)
        self.pushButton_divide = QtWidgets.QPushButton(self.widget)
        self.pushButton_divide.setAutoFillBackground(False)
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.gridLayout.addWidget(self.pushButton_divide, 2, 4, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.widget)
        self.pushButton_0.setAutoFillBackground(False)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 3, 0, 1, 1)
        self.pushButton_point = QtWidgets.QPushButton(self.widget)
        self.pushButton_point.setAutoFillBackground(False)
        self.pushButton_point.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_point.setObjectName("pushButton_point")
        self.gridLayout.addWidget(self.pushButton_point, 3, 1, 1, 1)
        self.pushButton_paranthesis_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_paranthesis_1.setAutoFillBackground(False)
        self.pushButton_paranthesis_1.setObjectName("pushButton_paranthesis_1")
        self.gridLayout.addWidget(self.pushButton_paranthesis_1, 3, 2, 1, 1)
        self.pushButton_paranthesis_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_paranthesis_2.setAutoFillBackground(False)
        self.pushButton_paranthesis_2.setObjectName("pushButton_paranthesis_2")
        self.gridLayout.addWidget(self.pushButton_paranthesis_2, 3, 3, 1, 1)
        self.pushButton_equal = QtWidgets.QPushButton(self.widget)
        self.pushButton_equal.setAutoFillBackground(False)
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.gridLayout.addWidget(self.pushButton_equal, 3, 4, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(lambda: self.display_text("1", self.lineEdit))
        self.pushButton_2.clicked.connect(lambda: self.display_text("2", self.lineEdit))
        self.pushButton_3.clicked.connect(lambda: self.display_text("3", self.lineEdit))
        self.pushButton_4.clicked.connect(lambda: self.display_text("4", self.lineEdit))
        self.pushButton_5.clicked.connect(lambda: self.display_text("5", self.lineEdit))
        self.pushButton_6.clicked.connect(lambda: self.display_text("6", self.lineEdit))
        self.pushButton_7.clicked.connect(lambda: self.display_text("7", self.lineEdit))
        self.pushButton_8.clicked.connect(lambda: self.display_text("8", self.lineEdit))
        self.pushButton_9.clicked.connect(lambda: self.display_text('9', self.lineEdit))
        self.pushButton_0.clicked.connect(lambda: self.display_text('0', self.lineEdit))
        self.pushButton_add.clicked.connect(lambda: self.display_text('+', self.lineEdit))
        self.pushButton_minus.clicked.connect(lambda: self.display_text('-', self.lineEdit))
        self.pushButton_multiply.clicked.connect(lambda: self.display_text('*', self.lineEdit))
        self.pushButton_divide.clicked.connect(lambda: self.display_text('/', self.lineEdit))
        self.pushButton_equal.clicked.connect(lambda: self.show_result(self.lineEdit))
        self.pushButton_paranthesis_1.clicked.connect(lambda: self.display_text('(', self.lineEdit))
        self.pushButton_paranthesis_2.clicked.connect(lambda: self.display_text(')', self.lineEdit))
        self.pushButton_percent.clicked.connect(lambda: self.clear(self.lineEdit))
        self.pushButton_point.clicked.connect(lambda: self.display_text(".", self.lineEdit))
        self.pushButton_exponent.clicked.connect(lambda: self.display_text('**', self.lineEdit))


    # IDK how it works but it works apparently to someone on github
    # ahhhhhhhhhhhh
    def clear(self, line_edit):
       line_edit.setText("")

    def display_text(self, value, line_edit):
        line_edit.setText(str(self.lineEdit.text()+value))

    def calculate_value(self, expression):
        try:
            result = eval(expression)
        except (ValueError, SyntaxError, ArithmeticError, SyntaxWarning):
            result = "Error: " + str(type(Exception))
        return result

    def show_result(self, line_exp):
        expression = line_exp.text()
        res = str(self.calculate_value(expression))
        line_exp.setText(res)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "1"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_multiply.setText(_translate("Form", "x"))
        self.pushButton_percent.setText(_translate("Form", "AC"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_exponent.setText(_translate("Form", "^"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_add.setText(_translate("Form", "+"))
        self.pushButton_divide.setText(_translate("Form", "/"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_point.setText(_translate("Form", "."))
        self.pushButton_paranthesis_1.setText(_translate("Form", "("))
        self.pushButton_paranthesis_2.setText(_translate("Form", ")"))
        self.pushButton_equal.setText(_translate("Form", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
