# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(1000, 700)
        Menu.setMinimumSize(QtCore.QSize(750, 500))
        Menu.setMaximumSize(QtCore.QSize(1000, 700))
        self.menu_bg_asset = QtWidgets.QLabel(Menu)
        self.menu_bg_asset.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        self.menu_bg_asset.setMinimumSize(QtCore.QSize(750, 500))
        self.menu_bg_asset.setMaximumSize(QtCore.QSize(1000, 700))
        self.menu_bg_asset.setText("")
        self.menu_bg_asset.setPixmap(QtGui.QPixmap("../Picture Assets/menu_bg.png"))
        self.menu_bg_asset.setScaledContents(True)
        self.menu_bg_asset.setObjectName("menu_bg_asset")
        self.back_bt = QtWidgets.QPushButton(Menu)
        self.back_bt.setGeometry(QtCore.QRect(30, 60, 141, 141))
        self.back_bt.setStyleSheet("QPushButton {border-radius: 70px;}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(125, 73, 229);\n"
"    }")
        self.back_bt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Picture Assets/back_bt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_bt.setIcon(icon)
        self.back_bt.setIconSize(QtCore.QSize(150, 165))
        self.back_bt.setFlat(True)
        self.back_bt.setObjectName("back_bt")
        self.challenge_bt = QtWidgets.QPushButton(Menu)
        self.challenge_bt.setGeometry(QtCore.QRect(92, 440, 402, 159))
        self.challenge_bt.setStyleSheet("QPushButton {border-radius: 20px;}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(198, 53, 104);\n"
"    }")
        self.challenge_bt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Picture Assets/challenge_bt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.challenge_bt.setIcon(icon1)
        self.challenge_bt.setIconSize(QtCore.QSize(400, 350))
        self.challenge_bt.setDefault(True)
        self.challenge_bt.setFlat(False)
        self.challenge_bt.setObjectName("challenge_bt")
        self.custom_bt = QtWidgets.QPushButton(Menu)
        self.custom_bt.setGeometry(QtCore.QRect(508, 440, 402, 159))
        self.custom_bt.setStyleSheet("QPushButton {border-radius: 20px;}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(198, 53, 104);\n"
"    }")
        self.custom_bt.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Picture Assets/custom_bt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.custom_bt.setIcon(icon2)
        self.custom_bt.setIconSize(QtCore.QSize(400, 350))
        self.custom_bt.setDefault(True)
        self.custom_bt.setFlat(False)
        self.custom_bt.setObjectName("custom_bt")
        self.arith_bt = QtWidgets.QPushButton(Menu)
        self.arith_bt.setGeometry(QtCore.QRect(92, 272, 402, 159))
        self.arith_bt.setStyleSheet("QPushButton {border-radius: 20px;}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(198, 53, 104);\n"
"    }")
        self.arith_bt.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Picture Assets/arith_bt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arith_bt.setIcon(icon3)
        self.arith_bt.setIconSize(QtCore.QSize(400, 350))
        self.arith_bt.setDefault(True)
        self.arith_bt.setFlat(False)
        self.arith_bt.setObjectName("arith_bt")
        self.geo_bt = QtWidgets.QPushButton(Menu)
        self.geo_bt.setGeometry(QtCore.QRect(508, 272, 402, 159))
        self.geo_bt.setStyleSheet("QPushButton {border-radius: 20px;}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(198, 53, 104);\n"
"    }")
        self.geo_bt.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Picture Assets/geo_bt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.geo_bt.setIcon(icon4)
        self.geo_bt.setIconSize(QtCore.QSize(400, 350))
        self.geo_bt.setDefault(True)
        self.geo_bt.setFlat(False)
        self.geo_bt.setObjectName("geo_bt")
        self.audio_bt = QtWidgets.QPushButton(Menu)
        self.audio_bt.setGeometry(QtCore.QRect(820, 60, 151, 151))
        self.audio_bt.setStyleSheet("QPushButton {border-radius: 70px;}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(125, 73, 229);\n"
"    }")
        self.audio_bt.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Picture Assets/audio_on_bt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audio_bt.setIcon(icon5)
        self.audio_bt.setIconSize(QtCore.QSize(140, 140))
        self.audio_bt.setFlat(True)
        self.audio_bt.setObjectName("audio_bt")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menu"))
        self.challenge_bt.setShortcut(_translate("Menu", "Return"))
        self.custom_bt.setShortcut(_translate("Menu", "Return"))
        self.arith_bt.setShortcut(_translate("Menu", "Return"))
        self.geo_bt.setShortcut(_translate("Menu", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QWidget()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
